# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
#    - sh buildsystem/install_buck.sh

language: android
jdk: oraclejdk8

android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-android-m2repository
    - extra-android-support

# Emulator Management: Create, Start and Wait
before_script:
#  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &
  - touch bintray.properties

script:
  - bash buildsystem/ci.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - bash file /bin/cat
  - bash more /home/travis/build/Piasy/AndroidTDDBootStrap/base/build/outputs/lint-results-debug.html

notifications:
  email:
    - xz4214@gmail.com

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
